/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:c995f811-725d-43b3-90df-d5fc584ee415",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_TXAYbIrxd",
    "aws_user_pools_web_client_id": "7ec6olr45dpni7domq1pccov18",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://5rzg3ckkirah3l4t56fjioggxa.appsync-api.sa-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "sa-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-symoblapfjg7bg6sn33qnbzbdq",
    "Analytics": {
        "disabled": true,
      }
};


export default awsmobile;
